<?php
/**
 * shippingcalculator
 *
 * @copyright Copyright © 2020 Landofcoder. All rights reserved.
 * @author    landofcoder@gmail.com
 */
?>


<?php
$helper = $this->helper('Lof\ShippingCalculator\Helper\Data');

if ($helper->getGeneralConfig('enable') == 1) {
    ?>
    <div class="product-add-form">
            <div id="block-shipping">
                <div class="shipping-p-20">
                    <div class="title-m-10">
                        <strong><?php echo $block->getData('title_shipping'); ?></strong>
                    </div>
                    <div class="description-b-b">
                        <p><?php echo $block->getData('description_shipping'); ?></p>
                    </div>
                        <div class="block-content">
                            <?php
                            if ($block->getData('country_enable') == 1) {
                                ?>
                            <label class="country m-t-b-10" for="country-label">
                                <span><b>Country</b></span>
                            </label>
                                <?php $countryBlock = $block->getLayout()->createBlock('Magento\Directory\Block\Data'); ?>
                                <?= $countryBlock->getCountryHtmlSelect($defValue = $block->getData('default_country'), $name = 'country_id', $id = 'country', $title = 'Country'); ?>
                            <?php
                            } ?>
                            <?php
                                if ($block->getData('state_region_enable') == 1) {
                                    ?>
                                    <label class="region-state m-t-b-10" for="country-label">
                                        <span><b>Region/State</b></span>
                                    </label>
                                    <div class="control">
                                        <input type="text" name="region_id" id="region-state" class="input-text validate-zip-international required-entry" value="<?php echo $block->getData('default_state_region'); ?>" aria-required="true">
                                    </div>
                                    <?php
                                } ?>
                            <?php if ($block->getData('zipcode_enable') == 1) {?>

                            <label class="postal-code m-t-b-10" for="country-label">
                            <span><b>Postal Code</b></span>
                                </label>
                                <div class="control">
                                    <input type="text" value="<?php echo $block->getData('default_zip_postcode'); ?>" name="postcode" id="postal-code" class="input-text validate-zip-international required-entry" aria-required="true">
                                </div>
                            <?php } ?>

                            <div class="shipping-button">
                                    <button type="submit" id="ajax-info-action shipping-calculate-button " class="action btn-danger submit shipping-calculate-button">
                                        <span><?php echo $block->getData('button_title'); ?></span>
                                    </button>
                                </div>
                        </div>
                </div>
            </div>
    </div>
    <?php
}
?>


<div class="ajax-info">
    <button id="ajax-info-action" type="button">Get Ajax Info</button>
</div>

<script type="text/x-magento-init">
{
    "#ajax-info-action":
    {
        "Lof_ShippingCalculator/js/hello": { }
    }
}
</script>


