<?php
/**
 * shippingcalculator
 *
 * @copyright Copyright © 2020 Landofcoder. All rights reserved.
 * @author    landofcoder@gmail.com
 */
?>

<?php
    $region = $block->getRegion();
?>

<?php $_product = $this->getProductInfo() ?>
<div class="product-add-form">
    <div id="block-shipping">
        <div id="shipping-cost-calculator" class="shipping-p-20">
            <div class="title-m-10">
                <h3><?php echo $block->getData('title_shipping'); ?></h3>
            </div>
            <div class="description-b-b">
                <p><?php echo $block->getData('description_shipping'); ?></p>
            </div>
            <div class="block-content">
                <?php
                if ($block->getData('country_enable') == 1) {
                    ?>
                    <label class="country m-t-b-10" for="country-label">
                        <span><b>Country</b></span>
                    </label>
                    <div class="control">
                        <?php $countryBlock = $block->getLayout()->createBlock('Magento\Directory\Block\Data'); ?>
                        <?= $countryBlock->getCountryHtmlSelect($defValue = $block->getData('default_country'), $name = 'country_id', $id = 'country', $title = 'Country'); ?>
                    </div>
                    <?php
                } ?>
                <?php
                if ($block->getData('state_region_enable') == 1) {
                    ?>
                    <label class="region-state m-t-b-10" for="country-label">
                        <span><b>Region/State</b></span>
                    </label>
                    <div class="control">
                        <?= $region ?>
                        <input type="hidden" name="region-state" id="region-state-input"
                               class="input-text validate-zip-international required-entry"
                               value="<?php echo $block->getData('default_state_region'); ?>" aria-required="true"></div>
                    <?php
                } ?>
                <?php if ($block->getData('zipcode_enable') == 1) { ?>

                    <label class="postal-code m-t-b-10" for="country-label">
                        <span><b>Postal Code</b></span>
                    </label>
                    <div class="control">
                        <input type="text"  minlength="8" maxlength="8" oninput="this.value=this.value.replace(/[^0-9]/g,'');" value="<?php echo $block->getData('default_zip_postcode'); ?>"
                               name="postcode" id="postcode"
                               class="input-text validate-zip-international required-entry" aria-required="true">
                    </div>
                <?php } ?>
                <div class="shipping-button">
                    <button id="btn-estimate-shipping" class="action btn-danger submit shipping-calculate-button">
                        <span><?php echo $block->getData('button_title'); ?></span>
                    </button>
                </div>
            </div>
            <ul id="shipping-estimate-results" style="display: none" class="shipping-estimate-results"></ul>
        </div>
    </div>
    <input type="hidden" name="lof_product_id" id="lof_product_id" value="<?= $_product->getId() ?>">
</div>

<script>
    require ([
            'jquery'
        ],
        function ($) {
            $(window).on("load", function () {
                require([
                    'estimaterates'
                ]);
            });
        });
</script>


<script>

    require([
        'jquery'
    ],function ($) {
        $(document).on('change','#country',function() {
            var param = 'country='+$('#country').val();
            console.log(param);
            $.ajax({
                showLoader: true,
                url: 'shippingcalculator/shippingrates/country',
                data: param,
                type: "GET",
                dataType: 'json'
            }).done(function (data) {
                $('#state').empty();
                if(data.value=='')
                {
                    $('#state').hide();
                    $('#region-state-input').show();
                }
                else
                {
                    $('#region-state-input').hide();
                    $('#state').append(data.value);
                    $('.field.states.required').hide();
                    $('.field.region.required').show();
                }
            });
        });
    })
</script>


